# FAIR principles

## What is FAIR?

::: mainfontFormat
In a nutshell, FAIR is a set of guiding principles to make data **F**indable, **A**ccessible, **I**nteroperable and **R**eusable.

The [FAIR principles](https://www.go-fair.org/fair-principles/) were first launched in 2014 at a [Lorentz Workshop](https://www.lorentzcenter.nl/) and officially published in 2016 with the focus on the EU's goal of increasing sharing and reusing of research data. [The implementation of the FAIR principles](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2019.172.01.0056.01.ENG) for research data is a requirement imposed by the EU, alongside the EU's request on Open Science & Open Data. It is noteworthy that the FAIR principles are not a standard.

### What is in it for you if you make your data FAIR? {.unnumbered}

The FAIR principles have multiple advantages for researchers. In general, by working in line with the FAIR principles, you can make your research more transparent, collaborative and sustainable and meanwhile facilitate your data management and protect your data's value for future use.

More specifically, you can expect the following by working with the FAIR principles:

-   Greater impact and visibility of your research.

-   Opportunities for new research collaborations.

-   More credit for yourself as a researcher.

-   A more efficient data management plan.

-   Possibilities for future research.

### What is in it for science if you make your data FAIR? {.unnumbered}

The FAIR principles also bring great benefits to the research community and thereby a fulfilling sense of community commitment to you as a researcher. FAIR principles:

-   Enhance scientific enquiry and debate.

-   Enable innovation and new data use.

-   Increase the efficiency of research due to reusability and replication studies.

-   Provide a valuable resource for education and training.

-   Encourage the improvement and validation of research methods.

-   Enable scrutiny of research results.

-   Facilitate transparency and accountability.
:::

## Key concepts to start with if you want to FAIRify your data

::: mainfontFormat
**PID (persistent identifier)**

A PID is a long-lasting reference to a document, a file, a web page or another object. It is usually used for digital objects that are accessible over the Internet but can also be used for physical objects. For example, the PID for a book can be its ISBN (International Standard Book Number). The use of a PID can effectively slow or prevent the damage of "link rot" in citations, which means that the cited URLs "go dead" because the contents are removed for different reasons.

You can encounter all kinds of PIDs in your research work. Here are two of the most frequently used types:

1.  **DOI (digital object identifier)**

The use of DOI is to identify academic and professional information, such as research articles, reports, datasets, publications -- and in some cases government documents and commercial videos.

Archiving your data with a data DOI as the PID will allow you to be compliant with the FAIR principles and enhance the impact of your research through increased visibility, leading to more citations.

You can read more about DOIs on the official website of the [International DOI Foundation](https://www.doi.org/) (IDF).

2.  **ORCID (open researcher and contributor ID)**

How can you find the work of one specific researcher among all the baffling names? ORCID might be your answer. ORCID provides a persistent identity for humans, so that a particular author's contributions to the literature or publications in the humanities can be easily and clearly recognized.

**Metadata**

In short, you can define Metadata as "data about data".

There are multiple categories of metadata with different definitions, while the following three are the most relevant to the FAIR principles.

○ **Descriptive metadata** are data that allow people to discover and identify them through the context or content, including title, author, abstract, keywords, etc.

○ **Structural metadata** are data about the project's internal structure and relationships to other objects, including the unit of analysis, data collection method, sampling procedure, etc.

○ **Administrative metadata** are data that are relevant for managing the project, including provenance, licence, creation date, file type, etc.

Metadata are not set out from the beginning and forgotten about. Instead, they are subject to changes and updates. Remember to add or modify your metadata continuously throughout the project.

Metadata can help you to play better with the FAIR principles, because metadata are machine-readable and, especially when they have a PID, search engines can easily find them.
:::

## Let's FAIR up!

::: mainfontFormat
**The principles**

The FAIR principles are quite straightforward. Below are the guidelines and you can read about the details for each at [the FAIR principles](https://www.go-fair.org/fair-principles/) website.

1.  **Findable**

F1. Metadata and data are assigned a globally unique and persistent identifier.

F2. Data are described with rich metadata (defined by R1 below).

F3. Metadata clearly and explicitly include the identifier of the data it describes.

F4. Metadata and data are registered or indexed in a searchable resource.

2.  **Accessible**

A1. Metadata and data are retrievable by their identifier using a standardised communications protocol:

  A1.1. The protocol is open, free and universally implementable.

  A1.2. The protocol allows for an authentication and authorization procedure, where necessary.

A2. Metadata are accessible, even when the data are no longer available.

3.  **Interoperable**

I1. Metadata and data use a formal, accessible, shared and broadly applicable language for knowledge representation.

I2. (Meta)data use vocabularies that follow FAIR principles:

  ○ Ontologies

  ○ Vocabularies

  ○ Taxonomies

I3. Metadata and data include qualified references to other (meta)data.

4.  **Reusable**

R1. Metadata and data are richly described with a plurality of accurate and relevant attributes:

  R1.1. Metadata and data are released with a clear and accessible data usage licence.

  R1.2. Metadata and data are associated with detailed provenance.

  R1.3. Metadata and data meet domain-relevant community standards.

**Step by step**

There are six FAIRification practices you can do to make your data FAIR.

○ Documentation

○ File formats

○ Metadata

○ Access to data

○ PID (persistent identifiers)

○ Data licences

**Documentation**

Documentation of data usually happens on two levels:

1.  Data-level documentation. At this level you should include information such as data type, data processing procedures, structure of the data, e.g., questions, variables, concepts, etc.
2.  Project-level (or study-level) documentation. At this level you should include information such as when, how and why the data were generated and by whom, how the data were processed, what quality assurance measures have been used, etc.

It is noteworthy that the lists are not exhaustive -- other information or data files are often included at both levels.

When it comes to publishing and reserving data, FAIR documentation enables you as a researcher to show how the data was generated and for what purpose by including information such as the following:

-   Methodology descriptions.

-   Codebooks.

-   Questionnaires.

-   Scripts like do-files editors (STATA).

-   Laboratory notebooks and experimental protocols.

-   Software syntax and output files.

-   Database schemes.

-   Provenance information about secondary data.

-   Finalised data management plan.

Publishing the documentation together with your data in a repository will boost the re-usability of your data and the likelihood of your data being cited -- thus more FAIR data.

**File formats**

Different file formats have different characteristics and properties. Some can have limitations. It is a good idea to decide the purpose of a file first -- for example, data collection/processing/analysis, reuse, or preservation -- as it helps to determine which format to use. Sometimes it can be handy to keep some data files in multiple formats.

When it comes to publishing and reserving data, you have to consider whether the file formats used for data collection, processing and analysis are also appropriate formats for long-term preservation. Furthermore, in the spirit of the FAIR principles, choose the right file format for publishing and preserving so that you and others can access and use the data later.

Here are some examples of preferred FAIR file formats for preservation:

-   Containers: TAR, GZIP, ZIP

-   Databases: XML, CSV, JSON

-   Geospatial: SHP, DBF, GeoTIFF, NetCDF

-   Video: MPEG, AVI, MXF, MKV

-   Sounds: WAVE, AIFF, MP3, MXF, FLAC

-   Statistics: DTA, POR, SAS, SAV

-   Images: TIFF, JPEG 2000, PDF, PNG, GIF, BMP, SVG

-   Tabular data: CSV, TXT

-   Text: XML, PDF/A, HTML, JSON, TXT, RTF

-   Web archive: WARC

**Metadata**

Earlier in this chapter, we learned about the concepts and categories of metadata, which play an important role in making your data FAIR. Remember to add metadata continuously to your research data, not just at the beginning or at the end of your project. You can read more about metadata standards and ontologies at [Dublin Core](https://www.dublincore.org/) and the [RDA Metadata Standards Directory Working Group](http://rd-alliance.github.io/metadata-directory/). Don't forget that your metadata must have a findable PID (persistent identifier) that is typically assigned when a digital resource is placed in a data repository.

**Access to data**

Always consider the following before you make your data accessible:

-   Who are the data available for and under which conditions?

-   How are the data backed up?

-   How is the above documented?

-   How may the Intellectual Property Rights (IPR) agreements restrict access to the data sets both during the collection and after finalising the project?

-   Do you and your collaborators agree on the 4 points above and the standard procedures and documents?

It might sound a little surprising that sensitive data, which include, for example, personal or confidential information, can also be FAIR without being open. Common practice is to anonymise (change to impersonal ID's) or de-identify (remove ID's) the data. However, this often comes with some limitations. For example, old, de-identified data cannot be added to new data after a certain period of time, which limits the reusability of the data.

**PID (persistent identifiers)**

Previously in this chapter, we have gained an understanding about PID (persistent identifiers). But how can you get a PID for your data and metadata? You can start with finding a repository that will provide a PID.

-   You may find something interesting and suitable for you on the list of repositories recommended by the [European Research Council](https://erc.europa.eu/funding-and-grants/managing-project/open-access).

-   You can visit [Re3data](https://www.re3data.org/), which is a global registry of research data repositories from various academic disciplines.

-   [FAIRsharing](https://fairsharing.org/search?fairsharingRegistry=Database) allows you to discover databases grouped by domain, species or organisation.

-   You can also check whether your institution has a local repository that can provide a PID for research data stored at their own local repository.

And there is a lot more if you still want to browse for other repositories, such as [OpenAIRE](https://explore.openaire.eu/participate/deposit/learn-how), [Figshare](https://figshare.com/), [ROAR](http://roar.eprints.org/), etc.

**Data licences**

A data licence is a legal arrangement between the creator of the data and the end-user/the place for data depositing, which specifies what users can do with the data. The most commonly used data licences are the suite of [Creative Commons](https://en.wikipedia.org/wiki/Creative_Commons) (CC) copyright licences, which concern reusability of the data and are irrevocable. Another widely known licence is [Copyright](https://en.wikipedia.org/wiki/Copyright). You can learn more about licences in the chapter "Open science policy, scientific integrity and ethics".
:::

## Test your understanding

<iframe src="https://sa1987.github.io/AgapeOSQuizChapter-6?embedded=true" width="100%" height="600" frameborder="0" marginheight="0" marginwidth="0" style="border: 3px solid #3fb5bd;">

Loading...

</iframe>

::: activitybox
::: center
**Activities**
:::

::: notification
In a recommend activities section like this one, we will recommend the activities to increase your understanding of the concepts and improve your practical knowledge.
:::

-   Find an online dataset and investigate how FAIR the dataset is:

    -   Findable -- Do PID's exist? Are metadata searchable?
    -   Accessible -- Are metadata and data retrievable?
    -   Interoperable -- Using open file format? API?
    -   Reusable -- Can you find the provenance, licence and description of data?

-   Try to answer the following questions:

    -   Will you consider making your data FAIR? Why/why not?
    -   What do you think the advantages/disadvantages could be?

-   Share your experience with FAIR principles in your research with others on our social media.
:::
